Remove constraint violations
sot/arc pull request #88
Opened 2024-12-11 15:50 UTC by taldcroft

## Description

The constraint violations reported in Replan Central are no longer valid:

- SCS-107 no longer stops maneuvers, so the attitude-based and momentum violations are incorrect.
- Bright star hold is no longer allowed as a safing action; instead Normal Sun Mode is activated if stars are lost. That means the constraint violations for that attitude are not relevant.

The expectation is that the load product generation will remove these constraints from the report in a future release. This PR fixes Replan Central in advance of that change.

## Interface impacts

## Functional testing

No functional testing.

2024-12-11 16:26 UTC, jeanconn commented
I think get_obsid_event can go too.

2025-01-28 20:12 UTC, jeanconn commented
I assume the "HRC proxy data stale
P4GM data stale
P41GM data stale"
on the test page is unrelated, but since I don't understand it based on the test setup, I can't approve the PR.  This probably just needs a new sync of the data and another run of the test code.

2025-01-28 20:12 UTC, jeanconn requested changes
Test output shows unexplained missing/stale data.

2025-01-28 21:43 UTC, taldcroft commented
> I assume the "HRC proxy data stale P4GM data stale P41GM data stale" on the test page is unrelated, but since I don't understand it based on the test setup, I can't approve the PR. This probably just needs a new sync of the data and another run of the test code.

The test functional docs say `This uses data files left over from PR 87.` This explains the stale data as being expected and unrelated to the PR.

2025-01-28 21:52 UTC, jeanconn commented
OK, though I think test setup comments like that should probably live outside of the copy-paste of shell commands and test deviations should be called out in the description.

2025-01-28 22:28 UTC, jeanconn approved these changes

2025-01-28 22:39 UTC, merged